
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/micro_doc
    username: postgres
    driver-class-name: org.postgresql.Driver
    password: docker
  jackson:
    time-zone: PRC
    date-format: "yyyy-MM-dd HH:mm:ss"

mybatis:
  mapper-locations: classpath*:/mybatis/*Mapper.xml
  type-aliases-package: wangju.microdoc.domain
  type-handlers-package: wangju.microdoc.typehandler
server:
  port: 9898



# 分页插件配置
pagehelper:
  # 分页插件会自动检测当前的数据库链接，自动选择合适的分页方式
  # mysql,mariadb,sqlite,hsqldb,postgresql,db2
  helper-dialect: postgresql
  # 分页合理化参数，默认值为false。当该参数设置为 true 时，pageNum<=0 时会查询第一页， pageNum>pages（超过总数时），会查询最后一页
  reasonable: true
  support-methods-arguments: true
  params: pageNum=page_num;pageSize=pageSize;count=countSql;reasonable=reasonable;pageSizeZero=pageSizeZero

